export default {
    // SHOPLIST ACTIONS
    GET_SHOPLIST_BY_ID: 'GET_SHOPLIST_BY_ID',
    GET_SHOPLIST_BY_SESSION_ID: 'GET_SHOPLIST_BY_SESSION_ID',
    CREATE_SHOPLIST: 'CREATE_SHOPLIST',
    UPDATE_SHOPLIST_BY_ID: 'UPDATE_SHOPLIST_BY_ID',
    UPDATE_SHOPLIST_BY_SESSION_ID: 'UPDATE_SHOPLIST_BY_SESSION_ID',

    GET_SHOPLIST_BY_ID_RESPONSE: 'GET_SHOPLIST_BY_ID_RESPONSE',
    GET_SHOPLIST_BY_SESSION_ID_RESPONSE: 'GET_SHOPLIST_BY_SESSION_ID_RESPONSE',
    CREATE_SHOPLIST_RESPONSE: 'CREATE_SHOPLIST_RESPONSE',
    UPDATE_SHOPLIST_BY_ID_RESPONSE: 'UPDATE_SHOPLIST_BY_ID_RESPONSE',
    UPDATE_SHOPLIST_BY_SESSION_ID_RESPONSE: 'UPDATE_SHOPLIST_BY_SESSION_ID_RESPONSE',

}
